FROM jupyter/pyspark-notebook:latest

USER root
WORKDIR /app

RUN pip install uv --no-cache-dir

COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev --frozen -v

COPY src/ ./src/
COPY main.py ./

RUN chown -R jovyan:users /app && \
    fix-permissions /home/jovyan

USER jovyan